[profile.default]
src = "src"
out = "out"
libs = ["lib", "lib/chainlink-ccip/chains/evm"]
remappings = [
  "@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v5.0.2/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=node_modules/@chainlink/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
]


[lint]
ignore = ["src/dependencies/*/*", "src/interfaces/pendle/*", "test/*"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
