[profile.default]
src = "src"
out = "out"
libs = ["lib", "lib/chainlink-ccip/chains/evm", "lib/chainlink-local", "lib/chainlink-local/lib/chainlink-evm"]
remappings = [
  "@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v5.0.2/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/src/v0.8/vendor/openzeppelin-solidity/v4.8.3/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/src/v0.8/shared/=lib/chainlink-local/lib/chainlink-evm/contracts/src/v0.8/shared/",
  "@chainlink/contracts/src/v0.8/=lib/chainlink-local/lib/chainlink-evm/contracts/src/v0.8/",
  "@chainlink/contracts/=node_modules/@chainlink/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
]


[lint]
ignore = ["src/dependencies/*/*", "src/interfaces/pendle/*", "test/*"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
